# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop
      - release-*
  paths:
    exclude:
      - .gitignore
      - CHANGELOG.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - .github/*

  tags:
    include: 
      - v*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

pool:
  vmImage: 'windows-latest'

variables:
  - group: sign-client-credentials
  - name: DOTNET_NOLOGO
    value: true  
  - name: buildPlatform
    value: 'Any CPU'  
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'nanoFramework.M2Mqtt.sln'
  - name: nugetPackageName
    value: 'nanoFramework.M2Mqtt'

steps:

  # build step only
  - template: azure-pipelines-templates/class-lib-build-only.yml@templates
    parameters:
      sonarCloudProject: 'nanoframework_paho.mqtt.m2mqtt'
      runUnitTests: false
      unitTestRunsettings: '$(System.DefaultWorkingDirectory)\.runsettings'

  # build the 2 libs step
  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.M2Mqtt'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.M2Mqtt.Core'

  # publish the 2 libs
  - template: azure-pipelines-templates/class-lib-publish.yml@templates

  # create GitHub release build from main branch
  - task: GithubRelease@1
    condition: >-
      and(
        succeeded(),
        eq(variables['System.PullRequest.PullRequestId'], ''),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/main'),
        not(contains(variables['Build.SourceBranch'], 'preview')),
        eq(variables['StartReleaseCandidate'], false)
      )
    displayName: Create/Update GitHub release
    inputs:
      action: edit
      gitHubConnection: 'github.com_nano-$(System.TeamProject)'
      tagSource: userSpecifiedTag
      tag: v$(MY_NUGET_VERSION)
      title: '$(nugetPackageName) Library v$(MY_NUGET_VERSION)'
      releaseNotesSource: inline
      releaseNotesInline: 'Check the [changelog]($(Build.Repository.Uri)/blob/$(Build.SourceBranchName)/CHANGELOG.md).<br><br><h4>Install from NuGet</h4><br>The following NuGet packages are available for download from this release:<br>:package: [nanoFramework.M2Mqtt](https://www.nuget.org/packages/$(nugetPackageName)/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION).<br>:package: [nanoFramework.M2Mqtt.Core (interface only)](https://www.nuget.org/packages/nanoFramework.M2Mqtt.Core/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION)'
      assets: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      assetUploadMode: replace
      isPreRelease: false
      addChangeLog: false


  # update dependents
  - template: azure-pipelines-templates/update-dependents.yml@templates  
    parameters:
      ${{ if eq(variables['UPDATE_DEPENDENTS'], 'false') }}:
        waitBeforeUpdate: false
      ${{ else }}:
        waitBeforeUpdate: true
      repositoriesToUpdate: |
        nanoFramework.Aws.IotCore.Devices
        nanoFramework.Azure.Devices

  # report error
  - template: azure-pipelines-templates/discord-webhook-task.yml@templates  
    parameters:
      status: 'failure'
      webhookUrl: '$(DiscordWebhook)'
      message: ''
